### ISSUE TITLE
Map-322 Suche nach Adressen

### ISSUE THREAD

**Issue by pkorduan** [pkorduan/lkrosmap#11]
Für die Suche wird ein Werkzeug angezeigt, welches eine Lupe und ein Gebäude daneben anzeigt. Beim Überfahren des Button mit der Maus wird ein Tooltip angezeigt, welches die Funktion beschreibt.
Die Suche nach Adressen mit Text erfolgt im Textfeld welches sich geöffnet hat, nachdem das Adresssuch- Werkzeug ausgewählt wurde. Eingegeben werden kann ein beliebiger Text mit Ort, Straße und Hausnummer.
Nach dem Absenden des Suchtextes durch einen Klick auf eine Lupe neben dem Eingabefeld erscheint an der Stelle der gefundenen Adresse ein Marker mit einem Info-Fenster daneben mit der angegebenen Adresse. Werden mehrere Adressen zum Suchtext gefunden werden diesen vorher in einer Auswahlliste unter dem Suchfeld zur Auswahl angezeigt.
Das Suchfeld verschwindet wieder, wenn ein anderes Werkzeug als das der Adresssuche aufgerufen wird.
Die Infofenster der Adressmarker enthalten einen Link mit dem das Fenster geschlossen und einen Link mit der der Marker gelöscht werden kann.
Für die Suchfunktion mit Text ist die Installation von Osm2po notwendig.

**Comment by holgerr** [comment]
- [x] Ergebnisse der Suche sollen erst angezeigt werden, wenn die Eingabe mit <Enter> oder mit einem Klick auf einem Button mit dem Begriff 'Los' geklickt wurde abgeschlossen wurde
- [x] Das Eingabefeld für die Ortssuche soll neben dem Button im Kartenfenster erscheinen. Damit soll das auf und ab der Karte vermieden werden.
- [x] Anordnung des Suchbuttons unterhalb des Abfragebuttons

**Comment by pkorduan** [comment]
Die Suceh nach Adressen ist fertig gestellt.
