### ISSUE TITLE
Map-325 Suche nach Sachdaten

### ISSUE THREAD

**Issue by pkorduan** [pkorduan/lkrosmap#14]
Für die Suche nach Sachdaten in den dargestellten Fach-Layern, wird ein Werkzeug angezeigt, welches ein Lupe mit einem i anzeigt. Beim Überfahren des Buttons mit der Maus wird ein Tooltip angezeigt, welches die Funktion beschreibt.
- [x] Werkzeug für die Sachdatensuche
Die Suche nach Sachdaten erfolgt im gleichen Textfeld wie die Adresssuche, nur muss der Button mit dem Marker vorher ausgewählt werden. Nach Click auf Los werden die zum Suchbegriff passenden Feature unter dem Textfeld zur Auswahl angezeigt. Durch einen Klick auf einen der angezeigten Features erscheint ein Marker in der Karte, der größer ist als der Original-Marker und ein Info-Fenster mit den Informationen zu diesem Objekt.
- [x] Suche nach Sachdaten über Eingabe von Begriffen
Wird ein Marker in der Karte angeklickt erscheint ebenfalls dieses Info-Fenster. Marker von Fachdaten können nicht entfernt werden, lediglich das Info-Fenster kann geschlossen werden.
Dieses Suchfunktion ist nur für WFS-Layer möglich. Für eine hochperformante Abfrage im Client werden die Daten aus dem WFS in einer GeoJSOn-Datei zwischengespeichert und deren Inhalt in einen Index überführt der Index wird mit der OpenSource Anwendung json2index (https://github.com/pkorduan/json2index) erzeugt und enthält eine Zuordnung von Wörtern zu Fachobjekten.
- [x] Anzeige der Sachdaten über InfoWindow bei Klick auf Symbol in Karte

**Comment by pkorduan** [comment]
Soll ich nun die Sachdatensuche so implementieren, dass nach Schlagwörtern aus denn WFS-Attributen gesucht werden kann, siehe Beschreibung oben? Also erst Begriff auswählen, dann mit Los suchen und dann das Feature aus einer Trefferliste auswählen. Das heist man kann zwar mehrere Feature finden, es wird aber immer nur ein Feature in der Karte angezoomed. Man kann nicht mehrere InfoFenster in der Karte gleichzeitig öffnen und darstellen.

Und noch eine Frage zur Anzeige der Infofenster. Wenn mehrere Feature eng beieinander oder übereinander in der Karte liegen. Sollen dann alle im Infofenster erscheinen? Aber mit welchem Suchradius? In https://gdi-service.de/pflegemap/ habe ich es so gemacht, dass der Suchkreis sich nach der Zoomstufe richtet und als Kreis um die Features angezeigt wird. Außerdem werden dann nicht gleich die Sachdaten alle angezeigt, sondern erst eine Vorschau der getroffenen Features und wenn man dann eines der anklickt erscheint die Info dazu über der Trefferliste. Schließt man das InfoFenster, verschwindet auch der Suchkreis. Klickt man ein Feature an, welches allein in der Karte steht wird gleich der Inhalt der Sachdaten im Infofenster angezeigt. Klick mal in https://gdi-service.de/pflegemap/ auf so einen Punkthaufen mit PD Symbolen.

**Comment by holgerr** [comment]
Peter, im Prinzip soll nach Schlagwörtern aus den WFS-Attributen gesucht werden, aus der Trefferliste wird das Feature ausgewählt und es wird nur der ausgewählte Treffer angezeigt.
Beim Überdenken der Sachdatensuche sind jedoch noch einigen Fragen aufgetaucht. 
- Wenn im Kartenfenster mehrere Layer aktiv sind, erfolgt die Suche über alle Layer oder wird der zu durchsuchende Layer vorher ausgewählt?
=> Die Suche erfolgt immer über alle Layer
- Werden alle Attribute der zu durchsuchenden Layer nach dem Suchbegriff durchsucht und die Treffer entsprechend dargestellt? 
=> Es werden nur die Attribute durchsucht, für die der Index erstellt wurde und welche das sind wird in der jeweiligen INI-Datei in der Anwendung json2index, mit der der Index erstellt wird festgelegt.
- Falls der Suchbegriff in mehreren Attributen des Layers enthalten ist, wird das gesuchte Feature mehrfach in der Trefferliste aufgelistet? - Bitte nur einmal auflisten
=> Der gefundene Datensatz wird nur einmal aufgeführt, weil er pro Suchbegriff nur ein mal im Index ist.
Die Anzeige der Informationen dicht beeinander liegender Features kann wie in der Pflegemap umgesetzt werden. Das ist gut gelungen.
Alternativ zum Klicken auf den Los-Button finde ich es gut, wenn die Suche zusätzlich mit Enter gestartet werden kann. Dann muss nach der Tastatureingabe nicht extra zu Maus gegriffen werden.

**Comment by pkorduan** [comment]
Hier müsste noch genauer festgelegt werden wie die Inhalte der einzelnen Features im InfoWindow aussehen sollen. Das lässt sich aber im Prinzip auch im nachhinein im Modell des Features in der dataFormatter festlegen.

**Comment by pkorduan** [comment]
Weitere Hinweise von holgerr
- [x] Symbole für Adress-/Objektsuche an den Anfang der Eingabezeile stellen, damit ist der Nutzer schon darauf hingewiesen, dass hier etwas auszuwählen geht, am Ende der Zeile ist das nicht immer gleich eindeutig, dass noch etwas anzuklicken ist.
- [x] Suchfeld oberhalb der ZoomIn und ZoomOut- Buttons anordnen und standardmäßig gleich geöffnet darstellen. Wenn dann auf das Lupensymbol geklickt wird, soll das Suchfeld geschlossen werden.
- [x] casesinsensitive gestalten, momentan muss auf Groß-/Kleinschreibung geachtet werden
- [x] Sprung auf das ausgewählte Objekt funktioniert nicht richtig, der Kartenausschnitt schießt über das Ziel hinweg, generell sollte der Kartenausschnitt so verschoben werden, dass das gesamt Info-Fenster zu sehen ist, beim Klick in die Karte zur Informationsanzeige funktioniert das auch noch nicht
Erledigt mit Commit 63f994

**Comment by pkorduan** [comment]
Für Punkte funktioniert das jetzt mit dem Highlighten durch Vergrößern.
- [x] Für Flächenobjekte muss jetzt auch noch ein Style zum Highlighten eingeführt werden. Dazu sind für jeden Geometrietyp default Styles zum Highlighten festzulegen, die in dem Modell überschrieben werden können.

**Comment by pkorduan** [comment]
Soll die Suche nach Features nur in Layern erfolgen, die gerade angeschaltet sind? Wenn nicht, soll beim Sprung auf ein Feature, welches gefunden wurde und zu einem nicht eingeschalteten Layer gehört und auf das gesprungen wird der dazugehörige Layer angeschaltet werden?
Antwort von M. Harms:
Die Suche nach Feature soll auch in ausgeschalteten Layern erfolgen und wenn auf ein Feature gesprungen wird, dessen Layer ausgeschaltet ist, dann soll dieser Layer angeschaltet werden.

**Comment by pkorduan** [comment]
Fertig mit commit 2cd44c0

**Comment by pkorduan** [comment]
Änderung zum Kommentar vom 30.3. in commit: fa3b39f

**Comment by holgerr** [comment]
Commentar wurde in Issue [Map-324](https://github.com/pkorduan/lkrosmap/issues/13) verschoben

**Comment by holgerr** [comment]
Sachdatenabfrage
Wenn das abzufragende Objekt am oberen Kartenrand liegt, wird beim Klick auf das Objekt das Informationsfenster nicht vollständig angezeigt oder es rutscht an den unteren Kartenrand und das Objekt ist nicht mehr zu sehen. Im ersteren Fall werden nicht alle Informationen angezeigt und der Schließen-Button ist nicht sichtbar, um ggf. das Infofenster zu schließen

**Comment by pkorduan** [comment]
- Suchergebnisse sollen mit einem Like Ausdruck %abc% gefunden werden können.

**Comment by pkorduan** [comment]
Das passiert schon automatisch wenn man nur einen Teil des Suchbegriffs eingibt, z.B. itzmo liefert auch Treffer für Kritzmow
