### ISSUE TITLE
Bug-2 Warnung vor gemischten Inhalten

### ISSUE THREAD

**Issue by holgerr** [pkorduan/lkrosmap#18]
Beim Aufruf von lkrosmap erhält man einen Warnhinweis bzgl. gemischter Inhalte. Ursache könnte m.E. der Aufruf von URL ohne https in den Dateien mapper.js Zeile 51, geocoder.js Zeile 175 und app.js Zeile 1, Zeile 28 sein. Ev. auch mapper.js in der Zeile 364. Ob die Photon-Api dann noch funktioniert ist noch zu testen.

**Comment by pkorduan** [comment]
Die Quellen für orka und die Ortssuche wurden auf https umgestellt in commit 3593cc4. Photon-Api wird nicht benutzt und in app.js Zeil1 und Zeile 28 werden nur relative Links für den Include im Header gesetzt. Die greifen auf https zu, wenn die Anwendung mit https aufgerufen wurde.
