### ISSUE TITLE
Map 326 - Sichtbarkeit der Layer Initialisieren

### ISSUE THREAD

**Issue by holgerr** [pkorduan/lkrosmap#19]
Die Sichtbarkeit der einzelnen Layer kann über einen Eintrag in der jeweiligen App-Datei (*.html) gesteuert werden. Dazu ist im jeweiligen Abschnitt der Layerkonfiguration der Eintrag `visible: false` bzw. `visible: true` vorzunehmen.
Damit im Layerswitcher die nicht sichtbaren Layer nicht angehakt sind, ist in der Datei ../js/controls/LayerSwitch/Control.js ab Zeile 29 folgende Änderung vorzunehmen
`- var html = '<input id="LkRosMap.checkLayerSwitch_' + index + '" type="checkbox" name="checkLayerSwitch_' + index + '" value="' + index + '" class="lkrosmap-check-layer-switch" checked> ' + layer.get('name');`
 `+     var checkVis = '';`
 `+     switch (layer.get('visible')) {`
 `+       case true:`
 `+         checkVis = 'checked';`
 `+         break;`
 `+       case false:`
 `+         checkVis = '';`
 `+         break;`
 `+       default:`
 `+         checkVis = 'checked'`
 `+       break;`
 `+     };`
 `+     var html = '<input id="LkRosMap.checkLayerSwitch_' + index + '" type="checkbox" name="checkLayerSwitch_' + index + '" value="' + index + '" class="lkrosmap-check-layer-switch" ' + checkVis + '> ' + layer.get('name');`

**Comment by pkorduan** [comment]
Änderungsvorschlag umgesetzt in Commit 8fc77ec allerdings durch setzen der visible Eigenschaft des Layers beim Erzeugen des Layers.
Folgendes in der Function createVectorLayers im mapper Controller hinzugefügt:
+ visible: (typeof layer_config.visible !== 'undefined' && !layer_config.visible ? false : true),
Wenn also visible = false oder 0 gesetzt ist ist der Layer beim Starten der Seite aus, sonst immer an.
