### ISSUE TITLE
Map-2: Erstellung des Grundgerüstes

### ISSUE THREAD

**Issue by pkorduan** [pkorduan/lkrosmap#2]
- [x] Erstellung des Grundgerüstes für die dynamische Darstellung von Karten
- [x] Einbindung einer Basiskarte
- [x] Layout für Suchfenster, Info-Fenster, Funktionsbutton, Hinweise, Sperren und Karte.

**Comment by pkorduan** [comment]
Suchergebnisfenster und Info-Fenster fehlen noch. Die werden aber dann in den Issues für die Suchfunktionen mit abgearbeitet.

**Comment by holgerr** [comment]
Button mit den Hinweisen, bisher rechts oben in der Ecke, bitte rechts unten überhalb des Copyright-Buttons anordnen
Um die Lesbarkeit der Buttons zu verbessern, die Buttons bitte etwas größer gestalten. In der bisherigen Anwendung mit ol2 sind die Buttons 22px groß, bitte übernehmen.
