### ISSUE TITLE
Titelleiste ausblenden

### ISSUE THREAD

**Issue by holgerr** [pkorduan/lkrosmap#20]
Das Kartenfenster wird in einem i-Frame eingebunden. Es ist daher keine eigene Titelleiste notwendig. Um das zu realisieren könnte, ist m.E. nach in der Datei lkrosmap/js/views/mapper/mapHeader.js der Code mit nachfolgenden Zeilen ausgetauscht werden:
`if (LkRosMap.config.hideHeader == true) {`
`  LkRosMap.views.mapper.mapHeader = {`
`    html: ""`
`  }`
`} else {`
`  LkRosMap.views.mapper.mapHeader = {`
`    html: "\`
`      <div id=\"LkRosMap.mapHeader\"> \`
`        <h1>Kartenthema: " + LkRosMap.config.name + "</h1> \`
`      </div> \`
`      "`
`  }`
`}`
In der jeweiligen ConfigDatei zum Kartenthema im Verzeichnis lkrosmap/apps ist unter config **hideHeader: true** einzutragen

**Comment by pkorduan** [comment]
Umgesetzt in commit aae8a1b. Es wird auch abgeprüft ob der Konfigurationsparameter überhaupt existiert. hideHeader muss also nicht zwangsweise gesetzt werden. Wenn er nicht gesetzt ist, wird der Titel auch angezeigt.
