### ISSUE TITLE
Größe des Mapfensters ändern

### ISSUE THREAD

**Issue by holgerr** [pkorduan/lkrosmap#21]
Durch die Vorgaben vom i-Frame in der übergeordneten Web-Site muss die Kartengröße wie folgt angepasst werden:

- lkrosmap/css/app.css - Zeile 4 - height: 720px;
- lkrosmap/css/app.css - Zeile 71 - height: 100%;

Dadurch passt das Kartenfenster besser in das i-Frame und die linke Bildlaufleiste wird nicht angezeigt.

**Comment by pkorduan** [comment]
Umgesetzt in commit 0b36cd8
