### ISSUE TITLE
Map-312: Layerswitcher

### ISSUE THREAD

**Issue by pkorduan** [pkorduan/lkrosmap#4]
- [x] Layer-Switcher über Button mit Auswahl mehrerer Hintergrund- und Informations-Layer
- [x] Eventhandler für die Checkboxen setzen und damit die Layer toggeln.

Welche Layer auswählbar sind wird in der Initialisierungs-Datei festgelegt, bzw. es werden immer alle auswählbar, die für die Karte definiert sind. Bei allen Layern wird definiert ob Hintergrund- oder Informations- Layer. Hintergrund-Layer sind immer nur über Radiobuttons auswählbar. Informations-Layer werden in der Reihenfolge überlagert dargestellt wie sie in der Initialisierungs-Datei festgelegt wurden. In der Reihenfolge erscheinen auch die Layer-Namen in der Legende.

**Comment by holgerr** [comment]
Layerswitcher bitte unterhalb der Suchbuttons auf der linken Seite anordnen

**Comment by pkorduan** [comment]
Fertig in commit 6212a73c5
