### ISSUE TITLE
Map-315: Einbau von Layern mit WFS bzw. GeoJSON

### ISSUE THREAD

**Issue by pkorduan** [pkorduan/lkrosmap#7]
- [x] WFS2JSON umbauen
So umbauen, dass variable WFS als Quelle angegeben werden können
- [x] Konvertierung der WFS-Attribute in GeoJson
Mappen der FeatureInfos nach GeoJson
- [x] Unterstützung von Linien und Flächenlayern in wfs2json
- [x] Unterstütung von Linien und Flächenlayern in den models von lkrosmap

**Comment by pkorduan** [comment]
Ich gehe richtig in der Annahme, dass alle Feature von Flächenlayern auch als Flächen gezeichnet werden sollen? Sollen die Gebietsgrenzen als Linien oder Flächenlayer gezeichnet werden, oder als Flächenlayer ohne Flächenfüllung und wenn mit Füllung wieviel Transparenz?
Das mit der Transparenz ist so eine Sache. Wenn man Kreise und Gemeinden und Gemarkungen und Fluren übereinander darstelle addiert sich die Transparenz so, dasss es dann doch nicht mehr Transparenz ist, wenn man alle Layer an hat. Außerdem ist fraglich welches Infofenster dann aufgehen soll, wenn Feature übereinander liegen. Oder sollen alle Infos der übereinanderliegenden Layer angezeigt werden. Wahrscheinlich letzteres.)

**Comment by holgerr** [comment]
Die Gebietsgrenzen sollen als Flächenlayer ohne Flächenfüllung gezeichnet werden. Das Farbschema ist [hier](https://www.landkreis-rostock.de/landkreis/kreisverwaltung/katasteramt/kartenthemen/gebietsgrenzen.html) nachvollziebar. In RGB sieht das dann so aus:
Fluren                 40 40 40
Gemarkung         90 90 170
Gemeindeteil     170 90 255
Gemeinde          255 0 0
Amtsverwaltung 0 0 255
Kreisgrenze         255 145 83
Genau, es sollen alle Infos der übereinanderliegenden **aktiven** Layer angezeigt werden.

**Comment by pkorduan** [comment]
Fertig
