### ISSUE TITLE
Map-317 Darstellung einer Legende

### ISSUE THREAD

**Issue by pkorduan** [pkorduan/lkrosmap#9]
- [x] Einbau Legende

**Comment by holgerr** [comment]
Den Button für die Legende bitte überhalb des Maßstabsbalkens auf der linken Seite anordnen. Den Button bitte mit 'Legende' beschriften.
Nach einem Klick auf den Button soll sich die Legende nach oben hin, in die Karte hinein, öffnen

**Comment by pkorduan** [comment]
Die Legende ist ja im Prinzip schon in dem Layerswitcher drin, siehe Karte Button "Ein- und Ausschalten von Layern und Legende". Soll trotzdem noch eine extra Legende dargestellt werden? Wenn ja sicher auch unterteilt in Layer und Klassen oder? Im Prinzip sieht die Legende dann so aus wie im Layerswitcher wenn alle Layer an sind, nur ohne Checkboxen.

**Comment by holgerr** [comment]
Unsere Vorstellung gehen dahin, dass im Layerswitcher die Symbole nicht dargestellt werden. Falls in einer Karte, wie z.B. bei den frühen Hilfen, viele Layer enthalten sind, wird das schnell unübersichtlich.
Die Legende soll nach Layer und Klassen unterteilt dargestellt werden. Falls die Legende zu groß wird, ca. ein Drittel von der Kartenhöhe, ist sie scrollbar zu gestalten, damit sie nicht mit den darüber liegenden Buttons und Boxen kollidiert.

**Comment by pkorduan** [comment]
Was soll in der Legende zu sehen sein, wenn Layer ausgeschaltet sind? Immer alle möglichen anzeigen?

**Comment by holgerr** [comment]
In der Legende sollen nur die in der Karte sichtbaren Overlay-Layer dargestellt werden. Die Hintergrundlayer erhalten keinen Eintrag in der Legende. Sollte keine Layer aktiv sein, ist die Legende auch leer, bis auf die Überschrift Legende. Im Prinzip wie beim Webauftritt von ORKa-MV.

**Comment by pkorduan** [comment]
Fertig
